# Generated by Django 5.1.6 on 2025-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('initiative', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('turn_index', models.IntegerField(default=0)),
                ('characters', models.ManyToManyField(to='initiative_tracker.character')),
                ('groups', models.ManyToManyField(blank=True, to='initiative_tracker.group')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='groups',
            field=models.ManyToManyField(blank=True, to='initiative_tracker.group'),
        ),
    ]
