# Generated by Django 5.1.6 on 2025-02-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
